API_ID       = 
API_HASH     = ""
BOT_TOKEN    = ""
SESSION      = ""
DATABASE_URI = "."
LOG_CHANNEL  = 
ADMIN        = 
CHANNEL      = ""
APPROVETEXT  = "Hello {mention}\nWelcome To {title}\n\nYour request has been approved"
APPROVE     = "on"
